# Generated by IBM TransformationAdvisor
# Thu Mar 10 14:43:18 UTC 2022

FROM ibmcom/websphere-traditional:latest-ubi

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/config/lib
COPY --chown=was:root samplemdbejbearmigrationbundle.zip /work/config/samplemdbejbearmigrationbundle.zip
COPY --chown=was:root ./src/config /work/config
COPY --chown=was:root ./lib /work/config/lib
RUN /work/configure.sh
